### ISSUE TITLE
DatePicker: using some date formats causes ParseException when formatting for editor

### ISSUE THREAD

**Issue by mee02** [DJ-Raven/swing-datetime-picker#11]
Formatting a date for the "editor" causes a `ParseException` in `MaskFormatter$MaskCharacter` when using some date formats.
This seems to apply to date formats in which a pattern letter does not directly correspond to a letter in the formatted date.

Example for reproduction: 
The default short date format for Locale `en_US` is `M/d/yy`, as returned from 
`((SimpleDateFormat) DateFormat.getDateInstance(DateFormat.SHORT)).toPattern()`.
Formatting a date with a two-digit month or day (e.g. 2024-11-24) causes a exception, leaving the editor `JFormattedTextField` empty.

**Comment by DJ-Raven** [comment]
Did you changed the format to `M/d/yy` ?
``` java
datePicker.setDateFormat("M/d/yy");
```
It not support to the editor input.

try
``` java
datePicker.setDateFormat("MM/dd/yy");
```
