### ISSUE TITLE
Add option to enable/disable component

### ISSUE THREAD

**Issue by omeniq** [DJ-Raven/swing-datetime-picker#13]
Hey, I really like your component to get modern date time picker! 
I'm missing one option - to enable/disable date time picker :-) I'm using it to show use date time picker to schedule a task for future execution. When time is counting I want to disable changing date time by user. Is it possible for you to implement setEnabled() method on your components?

Thanks!

**Comment by DJ-Raven** [comment]
@omeniq updated. you can use this option in `2.0.0-SNAPSHOT`: https://github.com/DJ-Raven/swing-datetime-picker#snapshots
