### ISSUE TITLE
TimePicker - setTimeSelectionAble is missing

### ISSUE THREAD

**Issue by omeniq** [DJ-Raven/swing-datetime-picker#14]
Hey Raven!

I found that there a method to "disable" some days selection with method _setDateSelectionAble()_ - this is great because I need to block dates before today so I can use 

`this.datePicker.setDateSelectionAble(localDate -> localDate.isAfter(LocalDate.now().minusDays(1))`

and this way every day before today (excluding today) user cannot select. 
I need to do the same with the time, but it is not possible now probably , am I right?
I would like block hours and minutes before _now()._

**Comment by DJ-Raven** [comment]
Updated. see this PR #15 
You can use this in `2.0.0-SNAPSHOT`: https://github.com/DJ-Raven/swing-datetime-picker#snapshots
