### ISSUE TITLE
AM/PM Problem

### ISSUE THREAD

**Issue by jorgegambini** [DJ-Raven/swing-datetime-picker#4]
Hello Ra-ven. Is there any possibility to correct the problem that exists in the TimePicker in 12Hs Mode in which the selected time is not reflected in the Formatted Field? This happens using the code downloaded from Github and also following the video code. Success in progress. Kind regards.

**Comment by DJ-Raven** [comment]
Maybe Error with Time zone, that format with `am` and `pm`. what time zone that you use in your PC ?

**Comment by jorgegambini** [comment]
Hi Raven... America/Buenos_Aires | Argentine Time

**Comment by jorgegambini** [comment]
You were right. It was solved by adding Locale.ENGLISH.

"private final DateTimeFormatter format12h = DateTimeFormatter.ofPattern("hh:mm a", Locale.ENGLISH);"

Thank you so much.

**Comment by DJ-Raven** [comment]
> "private final DateTimeFormatter format12h = DateTimeFormatter.ofPattern("hh:mm a", Locale.ENGLISH);"

Thank you :)
