### ISSUE TITLE
How to change the date format displayed in the editor

### ISSUE THREAD

**Issue by Curtaingit** [DJ-Raven/swing-datetime-picker#5]
```
        private JFormattedTextField dateText;
        dateText = new JFormattedTextField();
        DatePicker datePicker = new DatePicker();
        datePicker.setDateSelectionMode(DatePicker.DateSelectionMode.BETWEEN_DATE_SELECTED);
        datePicker.now();
        datePicker.setEditor(dateText);
```

I want to change the time display format，But my attempts to use `setText `or `addDateSelectionListener `didn't work

**Comment by DJ-Raven** [comment]
When you change the format to `dd-MMM-yyyy` it display `22-May-2024` or `25-Sept-2024` so we can't manage the input of `month` from the editor. or user hard to typing the `month`.

So I should update by add two different format. display format and input format.

**Comment by Curtaingit** [comment]
Thank you. I see what you mean.

**Comment by DJ-Raven** [comment]
I will close this issue when done update.

**Comment by Curtaingit** [comment]
Different regions may have different time format habits. Let's say I want to display something like `yyyy-MM-dd`.  Thank you for your support!

**Comment by Curtaingit** [comment]
thank you！
